name: dco

on:
  pull_request:

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check DCO sign-off on all commits in PR
        uses: tim-actions/dco@v1.1.0
